channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - matplotlib
  - pandas
  - rise
  - scipy
  - sympy
  - joblib
  
  - pip:
    - rolldecay-estimators
    - pyscores2
    - shipflowmotionshelpers