channels:
  - conda-forge
dependencies:
  - python<3.7
  - numpy
  - matplotlib
  - pandas
  - rise
  - scipy
  - sympy
  - joblib
  - seaborn
  
  - pip:
    - rolldecay-estimators==0.6.0
    - pyscores2
    - shipflowmotionshelpers